[package]
name = "elasticlean"
version = "0.4.0"
authors = ["jonathan gerber <jlgerber@gmail.com>"]
edition = "2018"

[dependencies]
pest ="2.1.0"
pest_derive="2.0"
chrono="0.4"
failure="0.1"
serde="1.0"
serde_json="1.0"
serde_derive="1.0"
reqwest="0.9"
structopt="0.2"
log="0.4"
env_logger="0.6"